version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "m2en"
      - "MikuroXina"
    target-branch: main
    commit-message:
      prefix: chore(npm)
    labels:
      - 'dependabot: update(npm)'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "m2en"
      - "MikuroXina"
    target-branch: main
    commit-message:
      prefix: chore(ci)
    labels:
      - 'dependabot: update(gh-actions)'
  - package-ecosystem: 'docker'
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "m2en"
      - "MikuroXina"
    target-branch: main
    commit-message:
      prefix: chore(docker)
    labels:
      - 'dependabot: update(docker)'
