version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "m2en"
      - "MikuroXina"
    target-branch: main
    commit-message:
      prefix: chore(npm)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "m2en"
      - "MikuroXina"
    target-branch: main
    commit-message:
      prefix: chore(ci)
  - package-ecosystem: 'docker'
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "m2en"
      - "MikuroXina"
    target-branch: main
    commit-message:
      prefix: chore(docker)
