# OreOreBot2 ラベルファイル
# ラベル等の編集はこのファイルを編集してください。 main ブランチ更新後 CI が動き出し同期を開始します。

# T - Packages Type
- name: 'T-@oreorebot2/common'
  description: 'Type: OreOreBot2 Common (packages/common)'
  color: 'FF8787'
- name: 'T-@oreorebot2/bot'
  description: 'Type: OreOreBot2 Bot (packages/bot)'
  color: '00b7c4'
- name: 'T-@oreorebot2/docs'
  description: 'Type: OreOreBot2 Docs (packages/docs)'
  color: 'D6FF74'

# C - Category
- name: 'C-bug'
  description: 'Category: bug'
  color: '8ec1f5'
- name: 'C-security'
  description: 'Category: security'
  color: '8ec1f5'
- name: 'C-enhancement'
  description: 'Category: enhancement'
  color: '8ec1f5'
- name: 'C-cleanup'
  description: 'Category: cleanup within codebase'
  color: '8ec1f5'
- name: 'C-GitHub Actions'
  description: 'Category: GitHub Actions'
  color: '8ec1f5'
- name: 'C-improvement'
  description: 'Category: improvement'
  color: '8ec1f5'
- name: 'C-development'
  description: 'Category: development'
  color: '8ec1f5'

# P - Priority
- name: 'P-high'
  description: 'Priority: High'
  color: 'f79d6d'

# R - Renovate

- name: 'R-Update(docker)'
  description: 'Renovate: update docker-image'
  color: '4d68b3'
- name: 'R-Update(gh-actions)'
  description: 'Renovate: update workflow'
  color: '4d68b3'
- name: 'R-Update(npm)'
  description: 'Renovate: update npm'
  color: '4d68b3'

- name: 'Need more Hibikiness'
  description: 'I need more Hibikiness in the message'
  color: '00b7c4'
- name: 'Help wanted'
  color: 'ab7aeb'
- name: 'good first issue'
  color: 'ab7aeb'
