# OreOreBot2 ラベルファイル
# ラベル等の編集はこのファイルを編集してください。 main ブランチ更新後 CI が動き出し同期を開始します。

# C - Category
- name: 'C-bug'
  description: 'Category: bug'
  color: '8ec1f5'
- name: 'C-security'
  description: 'Category: security'
  color: '8ec1f5'
- name: 'C-enhancement'
  description: 'Category: enhancement'
  color: '8ec1f5'
- name: 'C-cleanup'
  description: 'Category: cleanup within codebase'
  color: '8ec1f5'
- name: 'C-GHA (Actions)'
  description: 'Category: GitHub Actions'
  color: '8ec1f5'
- name: 'C-improvement'
  description: 'Category: improvement'
  color: '8ec1f5'
- name: 'C-development'
  description: 'Category: development'
  color: '8ec1f5'

# P - Priority
- name: 'P-high'
  description: 'Priority: High'
  color: 'f79d6d'
- name: 'P-medium'
  description: 'Priority: Medium'
  color: 'f79d6d'
- name: 'P-low'
  description: 'Priority: Low'
  color: 'f79d6d'

# N - Needs
- name: 'N-Discussion'
  description: 'Needs: Discussion'
  color: 'ff2929'
- name: 'N-More information'
  description: 'Needs: More information'
  color: 'ff2929'

# S - Status

- name: 'S-duplicate'
  description: 'Status: Duplicate'
  color: 'fcee6f'
- name: 'S-invalid'
  description: 'Status: Invalid'
  color: 'fcee6f'
- name: 'S-Needs specific case'
  description: 'Status: '
  color: 'fcee6f'
- name: 'S-Wrong'
  description: 'Status: Wrong'
  color: 'fcee6f'
- name: 'S-Wontfix'
  description: 'Status: Wontfix'
  color: 'fcee6f'

# R - Renovate

- name: 'R-Update(Docker)'
  description: 'Renovate: update docker-image'
  color: '4d68b3'
- name: 'R-Update(gh-actions)'
  description: 'Renovate: update workflow'
  color: '4d68b3'
- name: 'R-Update(npm)'
  description: 'Renovate: update npm'
  color: '4d68b3'

- name: 'Need more Hibikiness'
  description: 'I need more Hibikiness in the message'
  color: '00b7c4'
- name: 'Help wanted'
  description: ''
  color: 'ab7aeb'
- name: 'good first issue'
  description: ''
  color: 'ab7aeb'
