- name: 'bug'
  color: 'd73a4a'
- name: 'dependencies'
  color: '0366d6'
- name: 'documentation'
  color: 'E8E256'
- name: 'duplicate'
  color: 'cfd3d7'
- name: 'enhancement'
  color: 'a2eeef'
- name: 'good first issue'
  color: '7057ff'
- name: 'help wanted'
  color: '008672'
- name: 'improvement'
  color: 'fef2c0'
- name: 'invalid'
  color: 'e4e669'
- name: 'question'
  color: 'd876e3'
- name: 'refactoring'
  color: 'B8380F'
- name: 'released'
  color: 'ededed'
- name: 'specification change'
  color: 'FBCA04'
- name: 'wontfix'
  color: 'ffffff'
- name: 'workflows'
  color: 'F7ECBD'
- name: 'priority:Critical'
  color: 'B60205'
- name: 'priority:High'
  color: 'D93F0B'
- name: 'priority:Low'
  color: 'bfd4f2'
- name: 'priority:Medium'
  color: '1D76DB'
