env:
  node: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:markdown/recommended"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  project:
    - "./tsconfig.json"
plugins:
  - "@typescript-eslint"
  - "markdown"
rules:
  "sort-imports": "error"
overrides:
  - files: ["**/*.md"]
    processor: "markdown/markdown"
