env:
  node: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:markdown/recommended'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project:
    - './tsconfig.json'
plugins:
  - '@typescript-eslint'
  - 'markdown'
  - eslint-plugin-tsdoc
rules:
  'max-params': 'error'
  'tsdoc/syntax': 'warn'
overrides:
  - files: ['**/*.md']
    processor: 'markdown/markdown'
