env:
  node: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/strict-type-checked'
  - 'plugin:@typescript-eslint/stylistic-type-checked'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project: true
plugins:
  - '@typescript-eslint'
  - 'markdown'
  - eslint-plugin-tsdoc
rules:
  'max-params': 'error'
  'tsdoc/syntax': 'warn'
overrides:
  - files: ['**/*.md']
    processor: 'markdown/markdown'
root: true
