name: Publish
description: Publish the Docker package
inputs:
  major:
    description: Major version number
    required: true
  minor:
    description: Minor version number
    required: true
  patch:
    description: Patch version number
    required: true
  sha:
    description: Git SHA
    required: true

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.4.0

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          approvers/oreorebot2:latest
          approvers/oreorebot2:${{ inputs.sha }}
          approvers/oreorebot2:v${{ inputs.major }}
          approvers/oreorebot2:v${{ inputs.major }}.${{ inputs.minor }}
          approvers/oreorebot2:v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}
