name: Publish
description: Publish the Docker package
inputs:
  major:
    description: Major version number
    required: true
  minor:
    description: Minor version number
    required: true
  patch:
    description: Patch version number
    required: true
  sha:
    description: Git SHA
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/approvers/oreorebot2
        tags: |
          v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}
          v${{ inputs.major }}.${{ inputs.minor }}
          v${{ inputs.major }}
          ${{ inputs.sha }}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.4.0

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
