# GitHub Workflowsに関するプルリクエストに対し、reviewdogのlintを実行します。

name: Actionlint

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'

jobs:
  actionlint:
    name: actionlint with reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: actionlint
        uses: reviewdog/action-actionlint@v1.54.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
