# 作成されたプルリクエストに対し、.github/labeler.yml で定義されたラベルを自動付与します。

name: auto labeler
on:
  - pull_request_target

jobs:
  auto-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
