name: Auto Remove Priority Label

on:
  issues:
    types:
      - closed
  pull_request:
    types:
      - closed

jobs:
  remove-priority-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            Priority*Low
            Priority*Medium
            Priority*High
            Priority*Critical
