name: Dockerfile lint (OreOreBot2)

on:
  pull_request:
    paths-ignore:
      - 'Dockerfile'

jobs:
  lint:
    name: Dockerfile lint
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "No lint(dockerfile) required"
