# Dockerfileで定義されているDocker ImageをTrivyでスキャンし、GitHub Security にスキャン結果を送信します。

name: trivy scan

# プッシュ時とプルリクエスト時に実行する
on:
  push:
    # Dependabot のプッシュでの Workflows は読み取り専用権限として実行される
    # 上記の場合、Code Scanning は使用できないため Dependabot のプッシュはスキャン対象に含めない
    - '!dependabot/**/main/**'
    - main
  # プルリクエストは今まで通り、Dependabot のコミットであってもスキャン可能
  pull_request:

jobs:
  scan:
    name: Scan by Trivy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t oreorebot2 .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.8.0
        with:
          image-ref: 'oreorebot2'
          format: 'sarif'
          security-checks: vuln
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
