# OreOreBot2 Documents をビルドします。

name: Build (docs)

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build:
    name: Build (haracho.approvers.dev)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - name: Install packages
        run: yarn install --immutable
      - name: Build (haracho.approvers.dev)
        run: yarn run build
