# OreOreBot2 Documents に対して eslint を実行します。

name: eslint

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - name: Install packages
        run: yarn install --immutable
      - name: eslint
        run: yarn run lint
