# 作成されたプルリクエストに対してライセンスの変更がないか確認します。

name: License checker

on:
  pull_request:

jobs:
  run_license_checker:
    name: license-checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: pnpm

      - name: Install packages
        run: pnpm i --frozen-lockfile
      - name: license-checker
        run: npx @guidesmiths/license-checker --failOn /GPL/ --disableReport
