# 作成されたプルリクエストに対してライセンスの変更がないか確認します。

name: License checker

on:
  pull_request:

jobs:
  run_license_checker:
    name: license-checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install packages
        run: bun install --frozen-lockfile
      - name: license-checker
        run: bun x @guidesmiths/license-checker --failOn /GPL/ --disableReport
