name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          command: github-release

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - uses: docker/setup-buildx-action@v2.2.1

      - name: Build and publish Docker Images to GitHub Container registry
        uses: VaultVulp/gp-docker-action@1.5.0
        if: steps.release.outputs.release_created
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: oreorebot2
