# OreOreBot2 のDockerfile等をプッシュし、リリースします。

name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node

      - name: Publish the Docker package
        if: steps.release.outputs.release_created
        uses: ./.github/actions/publish
        with:
          major: ${{ steps.release.outputs.major }}
          minor: ${{ steps.release.outputs.minor }}
          patch: ${{ steps.release.outputs.patch }}
          sha: ${{ steps.release.outputs.sha }}
