# OreOreBot2 のDockerfile等をプッシュし、リリースします。

name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      major: ${{ steps.release.outputs['packages/bot--major'] }}
      minor: ${{ steps.release.outputs['packages/bot--minor'] }}
      patch: ${{ steps.release.outputs['packages/bot--patch'] }}
      sha: ${{ steps.release.outputs['packages/bot--sha'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.HIGUCHI_ICHIYO_APP_ID }}
          private_key: ${{ secrets.HIGUCHI_ICHIYO_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ steps.token.outputs.token }}

  publish:
    needs: release
    if: ${{ needs.release.outputs.releases_created == 'true' }}
    uses: ./.github/workflows/publish.yml
    permissions:
      contents: read
      packages: write
    with:
      major: ${{ needs.release.outputs.major }}
      minor: ${{ needs.release.outputs.minor }}
      patch: ${{ needs.release.outputs.patch }}
      sha: ${{ needs.release.outputs.sha }}
