name: Release
on:
  schedule:
    #        +---------------- minute (0 - 59)
    #        | +------------- hour (0 - 23)
    #        | | +---------- day of month (1 - 31)
    #        | | | +------- month (1 - 12)
    #        | | | | +---- day of week (0 - 6) (Sunday=0 or 7)
    #        | | | | |
    - cron: "0 3 * * 6" # At 12:00 on Saturday (JST)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - uses: docker/setup-buildx-action@v2.0.0
      - uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          tags: |
            ghcr.io/approvers/oreorebot2:${{ github.ref }}
            ghcr.io/approvers/oreorebot2:latest
