# OreOreBot2 のDockerfile等をプッシュし、リリースします。

name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.HIGUCHI_ICHIYO_APP_ID }}
          private_key: ${{ secrets.HIGUCHI_ICHIYO_PRIVATE_KEY }}

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ steps.token.outputs.token }}

      - name: Publish the Docker package
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        uses: approvers/OreOreBot2/.github/workflows/publish.yml@main
        with:
          major: ${{ steps.release.outputs['packages/bot--major'] }}
          minor: ${{ steps.release.outputs['packages/bot--minor'] }}
          patch: ${{ steps.release.outputs['packages/bot--patch'] }}
          sha: ${{ steps.release.outputs['packages/bot--sha'] }}
