name: Release PR
on:
  workflow_dispatch:
  schedule:
    #        +---------------- minute (0 - 59)
    #        | +------------- hour (0 - 23)
    #        | | +---------- day of month (1 - 31)
    #        | | | +------- month (1 - 12)
    #        | | | | +---- day of week (0 - 6) (Sunday=0 or 7)
    #        | | | | |
    - cron: "0 3 * * 6" # At 12:00 on Saturday (JST)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          command: release-pr
